Added preliminar support for Docker containers

diff --git a/orchestra/bin/orchestra-admin b/orchestra/bin/orchestra-admin
--- a/orchestra/bin/orchestra-admin
+++ b/orchestra/bin/orchestra-admin
@@ -149,7 +149,7 @@ function install_requirements () {
     # Install a more recent version of wkhtmltopdf (0.12.2) (PDF page number support)
     wkhtmltox=$(mktemp)
     wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb -O ${wkhtmltox}
-    dpkg -i ${wkhtmltox} || { echo "Installing missing dependencies for wkhtmltox..." && apt-get -f install; }
+    dpkg -i ${wkhtmltox} || { echo "Installing missing dependencies for wkhtmltox..." && apt-get -f -y install; }
     
     # Make sure locales are in place before installing postgres
     if [[ $({ perl --help > /dev/null; } 2>&1|grep 'locale failed') ]]; then
