Fixes on deployment

diff --git a/orchestra/bin/orchestra-admin b/orchestra/bin/orchestra-admin
--- a/orchestra/bin/orchestra-admin
+++ b/orchestra/bin/orchestra-admin
@@ -124,7 +124,7 @@ function install_requirements () {
          libcrack2-dev"
     
     # cracklib and lxml are excluded on the requirements.txt because they need unconvinient system dependencies
-    PIP="$(wget https://raw.githubusercontent.com/glic3rinu/django-orchestra/master/requirements.txt -q -O - | tr '\n' ' ') \
+    PIP="$(curl https://raw.githubusercontent.com/glic3rinu/django-orchestra/master/requirements.txt | tr '\n' ' ') \
         cracklib \
         lxml==3.3.5"
     
@@ -147,9 +147,11 @@ function install_requirements () {
     fi
     
     # Install a more recent version of wkhtmltopdf (0.12.2) (PDF page number support)
-    wkhtmltox=$(mktemp)
-    wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb -O ${wkhtmltox}
-    dpkg -i ${wkhtmltox} || { echo "Installing missing dependencies for wkhtmltox..." && apt-get -f -y install; }
+    if [[ $(dpkg --list | grep wkhtmltox | awk {'print $3'}) != "0.12.2.1" ]]; then
+        wkhtmltox=$(mktemp)
+        wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb -O ${wkhtmltox}
+        dpkg -i ${wkhtmltox} || { echo "Installing missing dependencies for wkhtmltox..." && apt-get -f -y install; }
+    fi
     
     # Make sure locales are in place before installing postgres
     if [[ $({ perl --help > /dev/null; } 2>&1|grep 'locale failed') ]]; then
